FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1

ENV COMFYUI_DIR=/opt/ComfyUI
ENV COMFYUI_MODEL_DIR=/models
ENV COMFYUI_OUTPUT_DIR=/outputs/comfyui
ENV XDG_CACHE_HOME=/cache
ENV HF_HOME=/cache/huggingface

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-dev \
    python3-venv \
    python3-pip \
    git \
    git-lfs \
    build-essential \
    ffmpeg \
    libgl1 \
    libglib2.0-0 \
    curl \
    wget \
    ca-certificates \
    nano \
    && rm -rf /var/lib/apt/lists/*

RUN git lfs install

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip setuptools wheel

RUN pip install \
    torch \
    torchvision \
    torchaudio \
    --index-url https://download.pytorch.org/whl/cu126

RUN git clone https://github.com/comfyanonymous/ComfyUI.git ${COMFYUI_DIR}

WORKDIR ${COMFYUI_DIR}

RUN pip install -r requirements.txt

RUN git clone https://github.com/ltdrdata/ComfyUI-Manager.git ${COMFYUI_DIR}/custom_nodes/ComfyUI-Manager

RUN cat > ${COMFYUI_DIR}/extra_model_paths.yaml <<'EOF'
runpod_models:
  base_path: /models
  checkpoints: checkpoints
  clip: clip
  clip_vision: clip_vision
  configs: configs
  controlnet: controlnet
  diffusion_models: diffusion_models
  embeddings: embeddings
  loras: loras
  upscale_models: upscale_models
  vae: vae
EOF

RUN mkdir -p \
    /models/checkpoints \
    /models/clip \
    /models/clip_vision \
    /models/configs \
    /models/controlnet \
    /models/diffusion_models \
    /models/embeddings \
    /models/loras \
    /models/upscale_models \
    /models/vae \
    /outputs/comfyui \
    /cache/huggingface \
    /workspace

EXPOSE 8188

WORKDIR ${COMFYUI_DIR}



## enable openssh
RUN apt-get update && apt-get install -y --no-install-recommends openssh-server \
 && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /run/sshd /root/.ssh \
 && chmod 700 /root/.ssh \
 && ssh-keygen -A \
 && sed -i 's/#\?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config \
 && sed -i 's/#\?PubkeyAuthentication .*/PubkeyAuthentication yes/' /etc/ssh/sshd_config \
 && sed -i 's/#\?PasswordAuthentication .*/PasswordAuthentication no/' /etc/ssh/sshd_config

COPY id_ed25519.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys


# install voice studio
RUN git clone https://github.com/FranckyB/Voice-Clone-Studio /opt/Voice-Clone-Studio && \
    sed -i "s/network_mode = _user_config.get('listen_on_network', False)/network_mode=True/g" /opt/Voice-Clone-Studio/voice_clone_studio.py && \
    cd /opt/Voice-Clone-Studio && \
    yes n | bash setup-linux.sh

EXPOSE 22

CMD ["python", "main.py", "--listen", "0.0.0.0", "--port", "8188", "--output-directory", "/outputs/comfyui"]
